import catchErrors from '../utils/tryCatch';

const getAllOldStudents = catchErrors(async (req, res) => {});
const getAnOldStudent = catchErrors(async (req, res) => {});

export { getAllOldStudents, getAnOldStudent };
